name: Build documentation for offline usage
on:
  workflow_dispatch:
  schedule:
    # Every week on Monday at midnight (UTC).
    # This keeps the generated HTML documentation fresh.
    - cron: '0 0 * * 1'
#  push:
#    branches:
#      - '3.5'

env:
  READTHEDOCS: True

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        branch: ["3.0", 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, stable, master]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Install dependencies
        run: |
          sudo pip3 install -r requirements.txt
          sudo pip3 install codespell

      # Build the HTML to upload it.
      - name: Sphinx build
        run: |
          READTHEDOCS=True sphinx-build --color -d _build/doctrees . _build/html -E

      - uses: actions/upload-artifact@v3
        with:
          name: godot-docs-html-${{ matrix.branch }}
          path: _build/html
          # Keep the current build and the previous build (in case a scheduled build failed).
          # This makes it more likely to have at least one successful build available at all times.
          retention-days: 15
